backend:
  name: test-repo # in-browser demo backend (no Git required)

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
