local_backend: true

backend:
  name: github
  repo: amoumouni/not-yo-mamas-magazine
  branch: main

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dxothvvut # <-- your cloud name
    api_key: 136962884118319 # <-- copy from dashboard (Product Environment Credentials)

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dxothvvut
    api_key: 136962884118319
    default_transformations:
      - - fetch_format: auto
          quality: auto
    upload_preset: nymm-articles
